name: lint
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DeLaGuardo/setup-clj-kondo@master
        with:
          version: '2021.12.16'
      - uses: 0918nobita/setup-cljstyle@v0.5.4
        with:
          cljstyle-version: 0.15.0
      - run: make lint
