name: test
on: [push]

jobs:
  test:
    strategy:
      matrix:
        java: ['11', '17']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - run: java -version
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: latest
      - uses: actions/cache@v2
        with:
          path: ~/.m2
          key: test-m2-${{ hashFiles('deps.edn') }}-v1
      - name: run test
        run: make test
